# Generated by Django 4.2 on 2023-04-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popular_women', '0002_alter_women_is_published_alter_women_time_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='women',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
