# Generated by Django 4.2 on 2023-04-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popular_women', '0003_women_content_women_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='women',
            name='category',
        ),
        migrations.AddField(
            model_name='women',
            name='categories',
            field=models.ManyToManyField(to='popular_women.category'),
        ),
    ]
