# Generated by Django 4.2 on 2023-04-18 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popular_women', '0004_remove_women_category_women_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Women',
            new_name='Woman',
        ),
    ]
